### ISSUE TITLE
Model __construct() declaration

### ISSUE THREAD

**Issue by jrean** [Torann/laravel-repository#13]
Hi,

First of all, thank you for your great package!

I'm trying to extend the `__construct()` method of one of my model to inject a dependency:

```
    /**
     * Constructor.
     *
     * @param  array  $attributes
     * @param  \League\CommonMark\Converter
     * @return void
     */
    public function __construct(array $attributes = [], Converter $converter)
    {
        parent::__construct($attributes);

        $this->converter = $converter;
    }
```

It raises this error:

```
Type error: Too few arguments to function App\Models\CategoryCity::__construct(), 0 passed in 
.../vendor/torann/laravel-repository/src/Repositories/AbstractRepository.php on line 478 and exactly 2 expected
```

Looking at `AbstractRepository.php on line 478`:

```
    /**
     * Create model instance.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     * @throws RepositoryException
     */
    public function makeModel()
    {
        if (!$this->model) {
            throw new RepositoryException("The model class must be set on the repository.");
        }

        return $this->modelInstance = with(new $this->model);
    }
```

Would you be kind to explain how should I do?

Thank you :-)

**Comment by Torann** [comment]
What is the `Converter` you're trying to inject? That's not part of *laravel-repository*

**Comment by Torann** [comment]
Documentation is here: http://lyften.com/projects/laravel-repository/doc/ 

Here is the usage: http://lyften.com/projects/laravel-repository/doc/usage.html

**Comment by jrean** [comment]
Hi @Torann, maybe my question is poorly detailed.
I'm just curious to understand how can I add a dependency into one of my Repository class (dependency injection) into the constructor method. Simple as that :-)

**Comment by Torann** [comment]
Should be able to do it the same way you do in other places in Laravel:

```php
<?php

namespace App\Repositories;

use App\Magic\FooInstance;
use Torann\LaravelRepository\Repositories\AbstractRepository;

class FooRepository extends AbstractRepository
{
    /**
     * @var FooInstance
     */
    protected $fooInstance;

    /**
     * Create a new Repository instance
     *
     * @param FooInstance $fooInstance
     */
    public function __construct(FooInstance $fooInstance)
    {
        parent::__construct();

        $this->fooInstance = $fooInstance;
    }
}
```

But that all depends on how you are calling the repositories. Should be fine if you are calling them like in my example controller [http://lyften.com/projects/laravel-repository/doc/usage.html](http://lyften.com/projects/laravel-repository/doc/usage.html)

**Comment by jrean** [comment]
Thank you :-)
