### ISSUE TITLE
Query on steroids

### ISSUE THREAD

**Issue by jrean** [Torann/laravel-repository#15]
Hi,

So I have something like I'm playing with:

(Models / Relations)
Company => Offices => City => Region => Country
Company => Subcategories => Category

Company Repository
```
    /**
     * Eager load the subcategory(ies).
     *
     * @return self
     */
    public function scopeWithSubcategories()
    {
        return $this->addScopeQuery(function($query) {
            return $query->with('subcategories');
        });
    }

    /**
     * Eager load the subcategory(ies) and categories.
     *
     * @return self
     */
    public function scopeWithSubcategoriesCategories()
    {
        return $this->addScopeQuery(function($query) {
            return $query->with('subcategories', 'subcategories.category');
        });
    }

    /**
     * Eager load the offices.
     *
     * @return self
     */
    public function scopeWithOffices()
    {
        return $this->addScopeQuery(function($query) {
            return $query->with(['offices', 'offices.city', 'offices.city.country']);
        });
    }
```

Let's say I want to fetch the Company with offices + category where office.city slug == XX and where category slug == YY

For testing purpose (without loading the relations) I ended with that:

```
        $companies = \App\Models\Company::whereHas('offices.city', function ($q) use($city) {
            $q->where('slug', $city->slug);
        })->whereHas('subcategories.category', function ($q) use($category) {
            $q->where('slug', $category->slug);
        })->get();
```

I desperately tried to do something like that with your package but hum... It makes no sense.

```
        $companies = $this->company
            ->withOffices()
            ->withSubcategoriesCategories()
            ->findWhere([
                'subcategories.category.id' => $category->id,
                'offices.city.id' => $city->id
        ]);
```

So my first question is how should I go to achieve my query... I'm very willing to understand :-)
Can we go step by step, please? (maybe even without the scopes)

Thank you for the awesome work.
If one day you find the time to provide alongside the documentation a list of advanced examples, it would be super awesome :-)

**Comment by Torann** [comment]
The scopes on the repositories are just for ease of use. I never intended them to work with nor do I use the `with` method in them. Here is an example oh how I usually do this type of thing:

```php
/**
 * Return all websites the given user can manage.
 *
 * @param  int $user_id
 * @return self
 */
public function scopeByUserAccess($user_id)
{
    return $this->addScopeQuery(function($query) use ($user_id) {
        $query = $query->leftJoin('website_managers', 'website_managers.website_id', '=', 'websites.id')
            ->select([
                'websites.*',
            ])
            ->where('website_managers.user_id', '=', $user_id)
            ->groupBy('websites.id');

        return $query;
    });
}
```

> Note: In the `select` method you can have it get columns from the joined table.

**Comment by stephenlake** [comment]
Thought this package as fantastic up until realising I couldn't use `->search()` with `->with()` relations without throwing in some selects, completely breaks the logic in using repositories to separate logic.

OP's comment hit the nail right on the head:
`but hum... It makes no sense.`

Why on earth?
`I never intended them to work with nor do I use the with method in them.`
