### ISSUE TITLE
Type error: Too few arguments to function App\Http\Controllers\AnnoncesUserController::afficherAnnoncesDetail(), 0 passed and exactly 1 expected

### ISSUE THREAD

**Issue by niaintsoa** [Torann/laravel-repository#20]
/**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function afficherAnnonces()
    {
        $annonces = Annonces::orderBy('created_at', 'desc')->paginate(3);
        return view('components.user-components.annonces')->with('annonces', $annonces);
    }

    public function afficherAnnoncesDetail($id)
    {
       dd($annonce = Annonces::find($id));
        // return view('components.user-components.annonce_detail')->with('annonce', $annonce);
    }

**Comment by niaintsoa** [comment]
Type error: Too few arguments to function App\Http\Controllers\AnnoncesUserController::afficherAnnoncesDetail(), 0 passed and exactly 1 expected

**Comment by Adenon** [comment]
did u solve it ?

**Comment by Torann** [comment]
There is no context on how this is being called. I feel it's not being use correctly. If you give me the controller so I can see how it's being called I can tell you what's doing on.

**Comment by fahad-imran** [comment]
[fontawesome-free-5.15.3-web (2).zip](https://github.com/Torann/laravel-repository/files/7074960/fontawesome-free-5.15.3-web.2.zip)
