### ISSUE TITLE
Adding with (RelationShips) method

### ISSUE THREAD

**Issue by rodmayes** [Torann/laravel-repository#22]
// In Torann\LaravelRepository\Repositories\AbstractRepository

 public function with($relations){
     if (is_string($relations)){
		  $relations = func_get_args();
		}
    return $this->addScopeQuery(function ($query) use ($relations ) {
      return $query->with($relations);
    });
}

**Comment by Torann** [comment]
You can extend the AbstractRepository in your project and add this or eager load them in your model. This isn't really something I'm looking to add to the package.
