### ISSUE TITLE
Compatible with Laravel 8.0

### ISSUE THREAD

**Issue by qtipee** [Torann/laravel-repository#31]
Hello, are you going to make this repository compatible with the latest version of Laravel any time soon ?

<img width="1116" alt="Screenshot 2020-09-14 at 13 23 54" src="https://user-images.githubusercontent.com/24697626/93080169-8c20c180-f68d-11ea-8a34-29f145d5a24c.png">

**Comment by xavierpantet** [comment]
Hello!

I would love to have it as well 😄 
Are you going to do it?

Thank you!

**Comment by timotheeduran** [comment]
Hi! Any news on this @Torann ?

**Comment by timotheeduran** [comment]
Oh! I noticed that you've updated the repo. So we can close this issue now?

**Comment by Torann** [comment]
Update with https://github.com/Torann/laravel-repository/releases/tag/0.6.0
