### ISSUE TITLE
Laravel 10 support 

### ISSUE THREAD

**Issue by stefanrakicfaxi** [Torann/laravel-repository#33]
Problem with upgrading to Laravel 10 

torann/laravel-repository 0.6.1 requires illuminate/database ^7.0|^8.24 -> found illuminate/database[v7.0.0, ..., v7.30.6, v8.24.0, ..., v8.83.27] but it conflicts with your root composer.json require (^9.0.0).

**Comment by Torann** [comment]
Added in v0.6.3

**Comment by stefanrakicfaxi** [comment]
@Torann thanks man :)
