### ISSUE TITLE
changing the lifetime of the cache

### ISSUE THREAD

**Issue by ayatamine** [Torann/laravel-repository#34]
Hi, when i wanted to override the cacheMinuts  in the repository like that:
/**
     * Lifetime of the cache.
     *
     * @var int
     */
    protected $cacheMinutes = 10;

i got this error 
Type of App\Repositories\CarBrandRepository::$cacheMinutes must be int (as in class Torann\LaravelRepository\Repositories\AbstractRepository)
Is there anything i have missed?

**Comment by Torann** [comment]
You need to make this `protected int $cacheMinutes = 10;`, you're missing the type declaration `int`
